export const AUTHENTICATION_OPTIONS = "AUTHENTICATION_OPTIONS";
export const USER_REPOSITORY = "USER_REPOSITORY";
export const PASSWORD_RESET_REPOSITORY = "PASSWORD_RESET_REPOSITORY";
export const CREATES_NEW_USERS = "CREATES_NEW_USERS";
export const UPDATES_USER_PASSWORDS = "UPDATES_USER_PASSWORDS";
export const UPDATES_USER_PROFILE = "UPDATES_USER_PROFILE";
export const RESETS_USER_PASSWORDS = "RESETS_USER_PASSWORDS";
